[workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
    "https://prefix.dev/robostack-humble",
]
platforms = ["osx-arm64", "linux-64", "win-64", "linux-aarch64"]
preview = ["pixi-build"]

[tasks]
sim = "ros2 run turtlesim turtlesim_node"
talker = "ros2 run talker_py talker"
navigator = "ros2 run navigator navigator"
navigator_py = "ros2 run navigator_py navigator"

[dependencies]
ros-humble-ros-core = ">=0.10.0,<0.11"
ros-humble-turtlesim = "*"
ros-humble-navigator = { path = "src/navigator/package.xml" }
ros-humble-navigator-py = { path = "src/navigator_py/package.xml" }
ros-humble-talker-py = { path = "src/talker-py/package.xml" }
