on: [push, pull_request]

jobs:
  install:
    name: Install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi environment
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          activate-environment: true

      - name: List ROS2 packages
        run: ros2 pkg list